
{{- if .Values.loadbalancer.enabled }}

apiVersion: v1
kind: Service
metadata:
{{- with .Values.loadbalancer.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 8161
    targetPort: http
  - name: core
    port: 61616
    targetPort: core
  - name: stomp
    port: 61613
    targetPort: 61613
  - name: amqp
    port: 5672
    targetPort: amqp
  type: LoadBalancer
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
  sessionAffinity: {{ .Values.loadbalancer.sessionAffinity | quote }}


{{- end }}
